### ISSUE TITLE
Tifinity fails on out of range tag type

### ISSUE THREAD

**Issue by pmay** [pmay/tifinity#1]
Real world TIFF seen with out of range tag. Requires more defensive parser programming.

Traceback (most recent call last):
  File "tifinity\__main__.py", line 52, in <module>
    main()
  File "tifinity\__main__.py", line 46, in main
    arguments.func(arguments)
  File "C:\Users\pmay\Repos\tifinity\tifinity\modules\compare_tiffs.py", line 30, in process_cli
    tiffs = [Tiff(args.tiff1), Tiff(args.tiff2)]
  File "C:\Users\pmay\Repos\tifinity\tifinity\parser\tiff.py", line 224, in __init__
    self.load_tiff()
  File "C:\Users\pmay\Repos\tifinity\tifinity\parser\tiff.py", line 250, in load_tiff
    ifd = self.read_ifd(nextifd_offset)
  File "C:\Users\pmay\Repos\tifinity\tifinity\parser\tiff.py", line 299, in read_ifd
    if count * ifdtype[tag_type][0] > 4:       # next 4 bytes are a pointer to the value's location
KeyError: 13

**Comment by pmay** [comment]
Adusted read_ifd method to retrieve tuple from ifdtype dictionary via dictionary get method, which returns None if an invalid type is queried for. Conditional branching allows handling of out of range tag types - directory entry is still read and a Directory object created with type_valid set to False. The directory entry's 4 byte value is read, but no determination can reliably be made as to whether this is a pointer or not. Printing of the directory entry now indicates invalid types with an "*" and a further annotation "[*Unknown Tag Type]"
