### ISSUE TITLE
Problem parsing big-endian TIFF files

### ISSUE THREAD

**Issue by pmay** [pmay/tifinity#2]
Traceback (most recent call last):
  File "C:\Users\pmay\Repos\tifinity\tifinity\parser\tiff.py", line 241, in load_tiff
    assert (self.magic == 42)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tifinity\__main__.py", line 52, in <module>
    main()
  File "tifinity\__main__.py", line 46, in main
    arguments.func(arguments)
  File "C:\Users\pmay\Repos\tifinity\tifinity\modules\tiff_details.py", line 17, in process_cli
    tiff = Tiff(args.file)
  File "C:\Users\pmay\Repos\tifinity\tifinity\parser\tiff.py", line 224, in __init__
    self.load_tiff()
  File "C:\Users\pmay\Repos\tifinity\tifinity\parser\tiff.py", line 243, in load_tiff
    raise InvalidTiffError("Incorrect header")
tifinity.parser.errors.InvalidTiffError: Incorrect header

**Comment by pmay** [comment]
Forgot to set _byteorder (call to set_byte_order) in TiffFileHandler
